### ISSUE TITLE
Request to add grunt option to modify variables

### ISSUE THREAD

**Issue by doogthemushroom** [ixrock/grunt-less2js#2]
Hey there, been using this task for awhile now and it's been working great! But, and without going too far into the details, now I need a way to set variables through grunt options. Something much like the [modifyVars option](https://github.com/gruntjs/grunt-contrib-less#modifyvars) from grunt-contrib-less. Actually modifyVars is the reason I need this option, since the variables I'm using less2js for are being changed at compile time by modifyVars. I'd be willing to do the changes required and submit it as a pull request but I wanted to know if you would be interested in it before I got started.

For example if this was my base file:

``` less
@base-color: #FF0000
@link-color: #FF9900
@other-color: #99FFCC
```

And if I wanted to use this option this is how I would write my task:

``` javascript
less2js: {
  colors2json: {
    options: {
      modifyVars: {
        'base-color': '#993399',
        'link-color': '#6666FF'
      },
    },
    files: {
      'dist/json/colors.json': 'src/less/base/variables/colors.less'
    }
  }
}
```

And the resulting file would look like:

``` json
{
  "base-color": "#993399",
  "link-color": "#6666FF",
  "other-color": "#99FFCC"
}
```

**Comment by ixrock** [comment]
Hi! Done with some new options in new version.
Enjoy! :P

**Comment by doogthemushroom** [comment]
Oh awesome! Thanks!

**Comment by doogthemushroom** [comment]
Ah using the option now I realize that it modifies the variables after all other options and after the less has been compiled. I really need this to happen before the less is compiled so I can use less functions in modifyVars. I should have provided better examples to showcase that.

**Comment by ixrock** [comment]
Hey! Implemented in new release! :)

**Comment by doogthemushroom** [comment]
Hot damn that was fast man, thanks! I'd send you some cookies right now if I could!

**Comment by ixrock** [comment]
:D
